"""Initial migration

Revision ID: a7932da89ca8
Revises: 
Create Date: 2025-09-16 23:26:34.253262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7932da89ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('propagation_method', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('planted_date', sa.Date(), nullable=False),
    sa.Column('expected_germination', sa.Date(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('watered', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_crops_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crops'))
    )
    op.create_index(op.f('ix_crops_current_stage'), 'crops', ['current_stage'], unique=False)
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_index(op.f('ix_crops_name'), 'crops', ['name'], unique=False)
    op.create_index(op.f('ix_crops_variety'), 'crops', ['variety'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_section', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_delivery', sa.Date(), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=False),
    sa.Column('current_stage_quantity', sa.Integer(), nullable=False),
    sa.Column('propagation_method', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('stage_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_client_name'), 'orders', ['client_name'], unique=False)
    op.create_index(op.f('ix_orders_crop_type'), 'orders', ['crop_type'], unique=False)
    op.create_index(op.f('ix_orders_current_section'), 'orders', ['current_section'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_variety'), 'orders', ['variety'], unique=False)
    op.create_table('budwood_collection',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('mother_tree_id', sa.String(length=50), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('storage_temperature', sa.Float(), nullable=True),
    sa.Column('storage_humidity', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_budwood_collection_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budwood_collection_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budwood_collection'))
    )
    op.create_index(op.f('ix_budwood_collection_harvest_date'), 'budwood_collection', ['harvest_date'], unique=False)
    op.create_index(op.f('ix_budwood_collection_id'), 'budwood_collection', ['id'], unique=False)
    op.create_index(op.f('ix_budwood_collection_variety'), 'budwood_collection', ['variety'], unique=False)
    op.create_table('order_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_stage_history_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_stage_history'))
    )
    op.create_index(op.f('ix_order_stage_history_id'), 'order_stage_history', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_tasks_crop_id_crops')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_tasks_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_task'), 'tasks', ['task'], unique=False)
    op.create_table('transfer_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('from_section', sa.String(length=50), nullable=False),
    sa.Column('to_section', sa.String(length=50), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('survival_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_transfer_records_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfer_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_records'))
    )
    op.create_index(op.f('ix_transfer_records_from_section'), 'transfer_records', ['from_section'], unique=False)
    op.create_index(op.f('ix_transfer_records_id'), 'transfer_records', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_records_to_section'), 'transfer_records', ['to_section'], unique=False)
    op.create_index(op.f('ix_transfer_records_transfer_date'), 'transfer_records', ['transfer_date'], unique=False)
    op.create_table('grafting_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('budwood_collection_id', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('technique', sa.String(length=50), nullable=False),
    sa.Column('rootstock_type', sa.String(length=100), nullable=False),
    sa.Column('scion_variety', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['budwood_collection_id'], ['budwood_collection.id'], name=op.f('fk_grafting_records_budwood_collection_id_budwood_collection')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_grafting_records_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grafting_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grafting_records'))
    )
    op.create_index(op.f('ix_grafting_records_date'), 'grafting_records', ['date'], unique=False)
    op.create_index(op.f('ix_grafting_records_id'), 'grafting_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grafting_records_id'), table_name='grafting_records')
    op.drop_index(op.f('ix_grafting_records_date'), table_name='grafting_records')
    op.drop_table('grafting_records')
    op.drop_index(op.f('ix_transfer_records_transfer_date'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_to_section'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_id'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_from_section'), table_name='transfer_records')
    op.drop_table('transfer_records')
    op.drop_index(op.f('ix_tasks_task'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_order_stage_history_id'), table_name='order_stage_history')
    op.drop_table('order_stage_history')
    op.drop_index(op.f('ix_budwood_collection_variety'), table_name='budwood_collection')
    op.drop_index(op.f('ix_budwood_collection_id'), table_name='budwood_collection')
    op.drop_index(op.f('ix_budwood_collection_harvest_date'), table_name='budwood_collection')
    op.drop_table('budwood_collection')
    op.drop_index(op.f('ix_orders_variety'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_current_section'), table_name='orders')
    op.drop_index(op.f('ix_orders_crop_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_name'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_crops_variety'), table_name='crops')
    op.drop_index(op.f('ix_crops_name'), table_name='crops')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_index(op.f('ix_crops_current_stage'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###