"""fix_multitenancy_constraints_and_relationships

Revision ID: cd0b9ecd07fa
Revises: 92918b9a284c
Create Date: 2026-02-09 21:01:01.089281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0b9ecd07fa'
down_revision = '92918b9a284c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_order_number')
        batch_op.create_index('ix_orders_order_number', ['order_number'], unique=False)
        batch_op.create_unique_constraint('uq_order_tenant_order_number', ['tenant_id', 'order_number'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_orders_po_number')
        batch_op.create_index('ix_purchase_orders_po_number', ['po_number'], unique=False)
        batch_op.create_unique_constraint('uq_po_tenant_po_number', ['tenant_id', 'po_number'])

    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tenant_user', ['tenant_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenant_user', type_='unique')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_po_tenant_po_number', type_='unique')
        batch_op.drop_index('ix_purchase_orders_po_number')
        batch_op.create_index('ix_purchase_orders_po_number', ['po_number'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_order_tenant_order_number', type_='unique')
        batch_op.drop_index('ix_orders_order_number')
        batch_op.create_index('ix_orders_order_number', ['order_number'], unique=True)
    # ### end Alembic commands ###